"use client";

import React, { useState } from 'react';
import Image from 'next/image';
import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const Footer = () => {
  const currentYear = new Date().getFullYear();
  const [activeModal, setActiveModal] = useState<null | 'privacy' | 'terms'>(null);

  const protocols = {
    privacy: {
      title: "PRIVACY PROTOCOL",
      content: "We treat your tactical data with high-altitude 256-bit isolation. No Personally Identifiable Information (PII) is shared with Mr. Predicto's neural network. Your engagement metrics and prediction history are used strictly to recalibrate the Arena Meta and improve the Global Accuracy Index. All strategic dossiers are encrypted at rest."
    },
    terms: {
      title: "TERMS OF ENGAGEMENT",
      content: "By entering the Cyber-Sports arena, you acknowledge that all predictions and analysis are for strategic engagement and entertainment purposes only. Cyber-Sports is a non-monetary competition designed for master-strategists. We do not support gambling. Misuse of the arena protocols or attempting to inject unauthorized logic into the scoring engine will result in immediate disqualification of your strategist identity."
    }
  };
  
  return (
    <>
    <footer className="relative w-full z-20 py-12 px-6 border-t border-white/5 bg-slate-950/20 backdrop-blur-sm">
      <div className="max-w-screen-2xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
        
        {/* Brand Section */}
        <div className="flex flex-col gap-4 items-center md:items-start">
          <div className="flex items-center gap-3">
            <div className="relative w-8 h-8 opacity-70">
              <Image src="/logo.png" alt="Logo" fill className="object-contain" sizes="32px" />
            </div>
            <span className="text-xl font-headline font-black italic tracking-tighter text-white/50 uppercase">
              Human <span className="text-primary/70">vs AI</span>
            </span>
          </div>
          <p className="text-[10px] uppercase font-black tracking-[0.2em] text-slate-500 text-center md:text-left">
            Neural Sports Logic v4.0.0
          </p>
        </div>

        {/* Legal & Copyright */}
        <div className="flex flex-col gap-2 items-center md:items-end">
          <p className="text-xs font-medium text-slate-400 text-center md:text-right">
            &copy; {currentYear} Sports AI Challenge. All Rights Reserved.
          </p>
          <div className="flex gap-4 text-[9px] uppercase font-black tracking-widest cursor-pointer">
            <button onClick={() => setActiveModal('privacy')} className="text-primary/40 hover:text-primary transition-colors hover:underline underline-offset-4 decoration-primary/50">Privacy Protocol</button>
            <span className="text-slate-800">/</span>
            <button onClick={() => setActiveModal('terms')} className="text-primary/40 hover:text-primary transition-colors hover:underline underline-offset-4 decoration-primary/50">Terms of Engagement</button>
          </div>
        </div>

      </div>

      {/* Deployment Disclaimer */}
      <div className="max-w-screen-2xl mx-auto mt-10 pt-6 border-t border-white/5 uppercase text-center">
        <p className="text-[8px] font-bold tracking-[0.3em] text-slate-600 max-w-2xl mx-auto leading-relaxed">
          The Cyber-Sports arena is designed for entertainment and strategic engagement purposes only. 
          All predictions are generated by AI models and do not guarantee outcomes. 
          Play for the pride, master the meta.
        </p>
      </div>
    </footer>

    {/* Deployment Protocol Modal (Privacy/Terms Overlay) */}
    <AnimatePresence>
      {activeModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6">
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setActiveModal(null)}
            className="absolute inset-0 bg-black/60 backdrop-blur-md"
          />
          
          <motion.div 
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="relative w-full max-w-lg p-8 glass-panel border border-primary/30 rounded-2xl shadow-[0_0_50px_rgba(129,236,255,0.15)] flex flex-col gap-6"
          >
            <div className="flex justify-between items-center pb-4 border-b border-white/10">
              <h2 className="font-headline font-black text-xl italic tracking-tighter text-white italic">
                SYSTEM <span className="text-primary">{protocols[activeModal].title}</span>
              </h2>
              <button 
                onClick={() => setActiveModal(null)}
                className="text-slate-500 hover:text-white transition-colors"
                aria-label="Close modal"
              >
                <X size={20} />
              </button>
            </div>
            
            <p className="text-slate-400 text-sm leading-relaxed font-medium uppercase tracking-tight">
              {protocols[activeModal].content}
            </p>
            
            <button 
              onClick={() => setActiveModal(null)}
              className="mt-4 w-full py-3 bg-primary/10 border border-primary/30 text-primary font-black uppercase text-xs tracking-widest hover:bg-primary/20 transition-all rounded"
            >
              Protocol Acknowledged
            </button>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
    </>
  );
};

export default Footer;
